export enum RoleName {
  Confesser = "Confesser",
  Bodyguard = "Bodyguard",
  Maniac = "Maniac",
  MafiaSilencer = "Mafia Silencer",
  MafiaInvestigator = "Mafia Investigator",
  MafiaRoleblocker = "Mafia Roleblocker",
  BlankRole = "Blank Role",
  Vetter = "Vetter",
  Judge = "Judge",
  Peacemaker = "Peacemaker",
  Framer = "Framer",
  Nimby = "Nimby",
  Tapper = "Tapper",
  Jailor = "Jailor",
  Sacrificer = "Sacrificer",
  Sniper = "Sniper",
  Lawman = "Lawman",
  Roleblocker = "Roleblocker",
  Investigator = "Investigator",
  Doctor = "Doctor",
  Mafia = "Mafia",
  Watchman = "Watchman",
  Tracker = "Tracker",
  Fortifier = "Fortifier",
}

export enum RoleGroup {
  Town = "town",
  Mafia = "mafia",
  Neutral = "neutral",
  Maniac = "maniac",
  Sniper = "sniper",
  Unaligned = "unaligned",
}
