/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./App.tsx",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./screens/**/*.{js,jsx,ts,tsx}",
    "./context/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "#060912",
        foreground: "#E9EEFF",
        card: "#0F1528",
        popover: "#0F1528",
        primary: "#5B8CFF",
        "primary-foreground": "#F2F6FF",
        secondary: "#19213A",
        "secondary-foreground": "#DCE5FF",
        muted: "#19213A",
        "muted-foreground": "#A8B4D9",
        accent: "#1E2947",
        "accent-foreground": "#E9EEFF",
        destructive: "#A93F57",
        "destructive-foreground": "#FFE7ED",
        border: "#283456",
        input: "#1E2947",
        ring: "#5B8CFF",
        success: "#3DDC97",
        chart1: "#4D7CFE",
        chart2: "#36D39E",
        chart3: "#E8B94A",
        chart4: "#B16CF3",
        chart5: "#F36A8F",
        surface: "#0F1528",
        "surface-muted": "#19213A",
        "text-primary": "#E9EEFF",
        "text-secondary": "#A8B4D9",
        danger: "#A93F57",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "32px",
      },
      borderRadius: {
        sm: "6px",
        md: "8px",
        lg: "12px",
        xl: "16px",
        "2xl": "20px",
      },
    },
  },
  plugins: [],
};
