"use client";
import { useEffect, useState } from "react"; import { createTRPCProxyClient, httpBatchLink } from "@trpc/client"; import superjson from "superjson"; import type { AppRouter } from "~/server/trpc/router"; import type { SocialUser } from "@mernmafia/shared/trpc/appRouter"; import { Input } from "./ui/input"; import { Button } from "./ui/button"; import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
const makeClient = () => createTRPCProxyClient<AppRouter>({ links: [httpBatchLink({ url: "/api/trpc", transformer: superjson })] });
export function Community() { const [client] = useState(makeClient); const [query, setQuery] = useState(""); const [users, setUsers] = useState<SocialUser[]>([]); const load = () => client.social.search.query({ query }).then(setUsers);
  // Initial discovery deliberately uses an empty query; later searches are form-driven.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(() => { void load(); }, []); async function act(user: SocialUser, action: "request" | "respond" | "remove" | "block") { if (action === "request") await client.social.request.mutate({ userId: user.id }); if (action === "respond") await client.social.respond.mutate({ userId: user.id, accept: true }); if (action === "remove") await client.social.remove.mutate({ userId: user.id }); if (action === "block") await client.social.block.mutate({ userId: user.id }); await load(); }
  return <Card><CardHeader><CardTitle>Players and friends</CardTitle></CardHeader><CardContent className="space-y-3"><form onSubmit={(e) => { e.preventDefault(); void load(); }} className="flex gap-2"><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search names or handles" /><Button>Search</Button></form>{users.map((user) => <div key={user.id} className="flex items-center justify-between rounded border p-3"><div><p className="font-medium">{user.name ?? "Player"}</p><p className="text-xs text-muted-foreground">{user.handle ? `@${user.handle}` : "No public handle"} · {user.relationship}</p></div><div className="flex gap-2">{user.relationship === "none" ? <Button size="sm" onClick={() => void act(user, "request")}>Add friend</Button> : null}{user.relationship === "incoming" ? <Button size="sm" onClick={() => void act(user, "respond")}>Accept</Button> : null}{user.relationship === "friend" ? <Button size="sm" variant="outline" onClick={() => void act(user, "remove")}>Remove</Button> : null}{user.relationship !== "blocked" ? <Button size="sm" variant="ghost" onClick={() => void act(user, "block")}>Block</Button> : null}</div></div>)}</CardContent></Card>;
}
