import { bodyguardDefinition as bodyguardDefinitionImpl } from "./town/bodyguard.js";
import { doctorDefinition as doctorDefinitionImpl } from "./town/doctor.js";
import { fortifierDefinition as fortifierDefinitionImpl } from "./town/fortifier.js";
import { investigatorDefinition as investigatorDefinitionImpl } from "./town/investigator.js";
import { jailorDefinition as jailorDefinitionImpl } from "./town/jailor.js";
import { judgeDefinition as judgeDefinitionImpl } from "./town/judge.js";
import { lawmanDefinition as lawmanDefinitionImpl } from "./town/lawman.js";
import { nimbyDefinition as nimbyDefinitionImpl } from "./town/nimby.js";
import { roleblockerDefinition as roleblockerDefinitionImpl } from "./town/roleblocker.js";
import { sacrificerDefinition as sacrificerDefinitionImpl } from "./town/sacrificer.js";
import { tapperDefinition as tapperDefinitionImpl } from "./town/tapper.js";
import { trackerDefinition as trackerDefinitionImpl } from "./town/tracker.js";
import { vetterDefinition as vetterDefinitionImpl } from "./town/vetter.js";
import { watchmanDefinition as watchmanDefinitionImpl } from "./town/watchman.js";

export const doctorDefinition = doctorDefinitionImpl;
export const investigatorDefinition = investigatorDefinitionImpl;
export const judgeDefinition = judgeDefinitionImpl;
export const watchmanDefinition = watchmanDefinitionImpl;
export const trackerDefinition = trackerDefinitionImpl;
export const tapperDefinition = tapperDefinitionImpl;
export const roleblockerDefinition = roleblockerDefinitionImpl;
export const bodyguardDefinition = bodyguardDefinitionImpl;
export const nimbyDefinition = nimbyDefinitionImpl;
export const sacrificerDefinition = sacrificerDefinitionImpl;
export const fortifierDefinition = fortifierDefinitionImpl;
export const jailorDefinition = jailorDefinitionImpl;
export const lawmanDefinition = lawmanDefinitionImpl;
export const vetterDefinition = vetterDefinitionImpl;
